code

diff --git a/test/run-functional-tests b/test/run-functional-tests
--- a/test/run-functional-tests
+++ b/test/run-functional-tests
@@ -4,7 +4,16 @@ DOCKER_IMAGE="liangxin1300/hatbw"
 DOCKER_SERVICE="docker.service"
 COROSYNC_CONF="/etc/corosync/corosync.conf"
 COROSYNC_AUTH="/etc/corosync/authkey"
-HA_NETWORK="ha_network"
+HA_NETWORK_FIRST="ha_network_first"
+HA_NETWORK_SECOND="ha_network_second"
+declare -a HA_NETWORK_ARRAY
+declare -a HA_NETWORK_V6_ARRAY
+HA_NETWORK_ARRAY[0]=$HA_NETWORK_FIRST
+HA_NETWORK_ARRAY[1]=$HA_NETWORK_SECOND
+HA_NETWORK_V6_ARRAY[0]="2001:db8:10::/64"
+HA_NETWORK_V6_ARRAY[1]="2001:db8:20::/64"
+BEHAVE_CASE_DIR="$(dirname $0)/features/"
+BEHAVE_CASE_EXCLUDE="sbd|ocfs2"
 read -r -d '' COROSYNC_CONF_TEMPLATE << EOM
 totem {
         version: 2
@@ -75,12 +84,11 @@ info() {
 
 is_number() {
 	num=$1
-	test ! -z "$num" && test "$num" -eq "$num" 2> /dev/null
+	test ! -z "$num" && test "$num" -eq "$num" 2> /dev/null && test "$num" -gt 0 2> /dev/null
 }
 
 
 check_docker_env() {
-	info "Checking docker environment..."
 	# check if docker available
 	systemctl list-unit-files $DOCKER_SERVICE &> /dev/null
 	if [ "$?" -ne 0 ];then
@@ -96,17 +104,30 @@ check_docker_env() {
 	if [ "$?" -ne 0 ];then
 		warning "docker cgroup driver suggest to be \"systemd\""
 	fi
-	echo
+
+	[ "$1" == "cleanup" ] && return
+	# check if ha network already exists
+	for network in ${HA_NETWORK_ARRAY[@]};do
+		docker network ls|grep -q "$network"
+		if [ "$?" -eq 0 ];then
+			fatal "HA specific network \"$network\" already exists"
+		fi
+	done
+}
+
+
+get_test_case_array() {
+	test -d $BEHAVE_CASE_DIR || fatal "Cannot find '$BEHAVE_CASE_DIR'"
+	ls $BEHAVE_CASE_DIR|grep "\.feature"|grep -Ev "$BEHAVE_CASE_EXCLUDE"
 }
 
 
 echo_test_cases() {
-	exclude_cases="sbd|ocfs2"
-	case_dir="$(dirname $0)/features/"
+	case_arry=`get_test_case_array`
 	echo "Index|File Name|Description"
 	index=1
-	for f in `ls $case_dir|grep "\.feature"|grep -Ev "$exclude_cases"`;do
-		desc=`awk -F: '/Feature/{print $2}' $case_dir/$f`
+	 for f in ${case_arry[@]};do
+		desc=`awk -F: '/Feature/{print $2}' $BEHAVE_CASE_DIR/$f`
 		printf "%3s    %-40s %-60s\n" $index $f "$desc"
 		index=$(($index+1))
 	done
@@ -123,71 +144,155 @@ OPTIONS:
   -h, --help	Show this help message and exit
   -l            List existing functional test cases and exit
   -n NUM        Only setup a cluster with NUM nodes(containers)
+  -c            Don't config corosync on containers(with -n option)
   -d            Cleanup the cluster containers
 END
 	exit 1
 }
 
 
-deploy_ha_node() {
-	node_name=$1
-	info "Deploying $node_name..."
-
-	docker run -d --name=$node_name --hostname $node_name --privileged --shm-size="1g" $DOCKER_IMAGE &> /dev/null
-	docker network connect $HA_NETWORK $node_name
-        docker exec -t $node_name /bin/sh -c "rm -rf /run/nologin"
-	docker exec -t $node_name /bin/sh -c "echo 'StrictHostKeyChecking no' >> /etc/ssh/ssh_config"
+docker_exec() {
+	name=$1
+	cmd=$2
+	docker exec -t $name /bin/sh -c "$cmd"
 }
 
 
-setup_cluster() {
+deploy_ha_node() {
+	node_name=$1
+	project_path=$(dirname $(dirname `realpath $0`))
+	docker_options="-d --name $node_name -h $node_name --privileged --shm-size 1g -v $project_path:/app"
+        build_cmd="cd /app;./autogen.sh && ./configure --prefix /usr && make install && make install-crmconfDATA prefix="
+
+	info "Deploying \"$node_name\"..."
+	docker run $docker_options $DOCKER_IMAGE &> /dev/null
+	for network in ${HA_NETWORK_ARRAY[@]};do
+		docker network connect $network $node_name
+	done
+
+	docker_exec $node_name "rm -rf /run/nologin"
+	docker_exec $node_name "echo 'StrictHostKeyChecking no' >> /etc/ssh/ssh_config"
+	info "Building crmsh codes on \"$node_name\"..."
+	docker_exec $node_name "$build_cmd" 1> /dev/null || \
+		fatal "Building failed!"
+}
+
+
+create_node() {
 	info "Loading docker image $DOCKER_IMAGE..."
         docker pull $DOCKER_IMAGE &> /dev/null
 
-	info "Create ha specific docker network $HA_NETWORK..."
-	docker network create $HA_NETWORK &> /dev/null
-	info "Setup cluster..."
-
-	for i in $(seq 1 $1);do
-		deploy_ha_node hanode$i
+	for index in ${!HA_NETWORK_ARRAY[@]};do
+		network=${HA_NETWORK_ARRAY[$index]}
+		info "Create ha specific docker network \"$network\"..."
+		docker network create --ipv6 --subnet ${HA_NETWORK_V6_ARRAY[$index]} $network &> /dev/null
 	done
 
+	info "Setup cluster..."
+	for node in $*;do
+		deploy_ha_node $node
+	done
+}
+
+
+config_cluster() {
+	node_num=$#
 	insert_str=""
-	container_ip_array=(`docker network inspect $HA_NETWORK -f '{{range .Containers}}{{printf "%s " .IPv4Address}}{{end}}'`)
-	for i in $(seq $1 -1 1);do
+	container_ip_array=(`docker network inspect $HA_NETWORK_ARRAY -f '{{range .Containers}}{{printf "%s " .IPv4Address}}{{end}}'`)
+
+	for i in $(seq $node_num -1 1);do
 		ip=`echo ${container_ip_array[$((i-1))]}|awk -F/ '{print $1}'`
 		insert_str+="\\n\\tnode {\n\t\tring0_addr: $ip\n\t\tnodeid: $i\n\t}"
 	done
 	corosync_conf_str=$(sed "/nodelist/a \\${insert_str}" <(echo "$COROSYNC_CONF_TEMPLATE"))
-	if [ ${#container_ip_array[@]} -eq 2 ];then
+	if [ $node_num -eq 2 ];then
 		corosync_conf_str=$(sed "/corosync_votequorum/a \\\\ttwo_node: 1" <(echo "$corosync_conf_str"))
 	fi
 
-	for i in $(seq 1 $1);do
-		docker exec -t hanode$i /bin/sh -c "echo \"$corosync_conf_str\" >> $COROSYNC_CONF"
-		if [ $i -eq 1 ];then
-			docker exec -t hanode1 /bin/sh -c "corosync-keygen -l -k $COROSYNC_AUTH &> /dev/null"
+	for node in $*;do
+		if [ $node == $1 ];then
+			docker_exec $1 "echo \"$corosync_conf_str\" >> $COROSYNC_CONF"
+			docker_exec $1 "corosync-keygen -l -k $COROSYNC_AUTH &> /dev/null"
 		else
-		        docker exec -t hanode1 /bin/sh -c "scp -p $COROSYNC_AUTH hanode$i:/etc/corosync &> /dev/null"
+			docker_exec $1 "scp -p $COROSYNC_CONF $COROSYNC_AUTH $node:/etc/corosync &> /dev/null"
 		fi
-		docker exec -t hanode$i /bin/sh -c "crm cluster start"
 	done
+}
+
+
+start_cluster() {
+	for node in $*;do
+		docker_exec $node "crm cluster start"
+	done
+}
+
+
+container_already_exists() {
+	docker ps -a|grep -q "$1"
+	if [ "$?" -eq 0 ];then
+		fatal "Container \"$1\" already running"
+	fi
+}
+
+
+setup_cluster() {
+	hanodes_arry=()
+	is_number $1
+	if [ "$?" -eq 0 ];then
+		for i in $(seq 1 $1);do
+			hanodes_arry+=("hanode$i")
+		done
+	else
+		hanodes_arry=($*)
+	fi
+
+	create_node ${hanodes_arry[@]}
+	[ "$CONFIG_COROSYNC_FLAG" -eq 0 ] && return
+	config_cluster ${hanodes_arry[@]}
+	start_cluster ${hanodes_arry[@]}
 }
 
 
 cleanup_cluster() {
-	container_array=(`docker network inspect $HA_NETWORK -f '{{range .Containers}}{{printf "%s " .Name}}{{end}}'`)
+	exist_network_array=()
+	for network in ${HA_NETWORK_ARRAY[@]};do
+		docker network ls|grep -q $network && exist_network_array+=($network)
+	done
+	if [ ${#exist_network_array[@]} -eq 0 ];then
+		info "Already cleaned up"
+		return 0
+	fi
+
+	container_array=(`docker network inspect $exist_network_array -f '{{range .Containers}}{{printf "%s " .Name}}{{end}}'`)
 	for node in ${container_array[@]};do
-		info "Cleanup container $node..."
+		info "Cleanup container \"$node\"..."
 		docker container stop $node &> /dev/null
 		docker container rm $node &> /dev/null
 	done
-	info "Cleanup ha specific docker network $HA_NETWORK..."
-	docker network rm $HA_NETWORK &> /dev/null
+
+	for network in ${exist_network_array[@]};do
+		info "Cleanup ha specific docker network \"$network\"..."
+		docker network rm $network &> /dev/null
+	done
 }
 
 
-options=$(getopt -l "help" -o "hldn:" -- "$@")
+adjust_test_case() {
+	replace_arry=(`docker_exec hanode1 "grep -o -E @hanode[0-9]+\.ip\.[0-9] $1"|sort -u|dos2unix`)
+	for item in ${replace_arry[@]};do
+		item_str=${item##@}
+		node=`echo $item_str|awk -F. '{print $1}'`
+		index=`echo $item_str|awk -F. '{print $3}'`
+		ip=`docker container inspect $node -f "{{.NetworkSettings.Networks.${HA_NETWORK_ARRAY[$index]}.IPAddress}}"`
+		docker_exec hanode1 "sed -i s/$item/$ip/g $1"
+	done
+	default_ip=`docker container inspect hanode1 -f '{{range .NetworkSettings.Networks}}{{printf "%s " .IPAddress}}{{end}}'|awk '{print $1}'`
+	docker_exec hanode1 "sed -i -E s/@hanode[0-9]+.ip.default/$default_ip/g $1"
+}
+
+
+CONFIG_COROSYNC_FLAG=1
+options=$(getopt -l "help" -o "hldcn:" -- "$@")
 eval set -- "$options"
 while true;do
 case $1 in
@@ -197,12 +302,18 @@ case $1 in
 	exit 0
 	;;
 -d)
+	check_docker_env cleanup
 	cleanup_cluster
 	exit $?
 	;;
--n)
+-c)
+	CONFIG_COROSYNC_FLAG=0
 	shift
-	is_number $1 || fatal "-n option need a number"
+	;;
+-n)
+	check_docker_env
+	shift
+	is_number $1 || fatal "-n option need a number larger than 0"
 	setup_cluster $1
 	exit $?
 	;;
@@ -213,17 +324,33 @@ case $1 in
 esac
 done
 
-if [ -z "$1" ];then
+if [ "$#" -eq 0 ];then
 	usage_and_exit
 fi
 
-test_case_index=$1
-if [ -n "$test_case_index" ];then
-	echo_test_cases|grep -E "\s+$test_case_index\s" &> /dev/null
+for case_num in $*;do
+	echo_test_cases|grep -E "\s+$case_num\s" &> /dev/null
 	if [ "$?" -ne 0 ];then
-		error "\"$test_case_index\" is an invalid index"
+		error "\"$case_num\" is an invalid index"
 		echo_test_cases
+		exit 1
 	fi
-fi
+done
 
-check_docker_env
+for case_num in $*;do
+	if [ "$case_num" -ne $1 ];then
+		check_docker_env cleanup
+		cleanup_cluster
+		echo
+	fi
+	check_docker_env
+	test_case_array=(`get_test_case_array`)
+	case_file=$BEHAVE_CASE_DIR/${test_case_array[$((case_num-1))]}
+	case_file_in_container="/app/test/features/`basename $case_file`"
+	node_arry=(`awk -F: '/Need nodes/{print $2}' $case_file`)
+	CONFIG_COROSYNC_FLAG=0
+	setup_cluster ${node_arry[@]}
+	adjust_test_case $case_file_in_container
+	docker_exec hanode1 "behave $case_file_in_container"
+	echo
+done
